### ISSUE TITLE
Failing to run it on macOS 

### ISSUE THREAD

**Issue by rudym** [zesterer/teloren#14]
Hi, can you help, please?
Is teloren supposed to work on macOS?

Trying to debug it, but it is failing with the error:
```
thread 'main' panicked at 'Failed to create client instance: 
StreamErr(Deserialize(Custom("invalid value: integer `1050253722`, expected variant index 0 <= i < 3")))', 
src/main.rs:117:10
```

**Comment by zesterer** [comment]
Hey, that sounds like you need to update the internal client. You can do that using `cargo update`.

**Comment by rudym** [comment]
oh, cheers
